name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    - name: Create Package
      uses: BigWigsMods/packager@master
      env:
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: -m .pkgmeta